---
apiVersion: v1
kind: Namespace
metadata:
  name: blue-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-blue
  namespace: blue-app
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: webapp
        image: robokingmaster/examples:colorapp
        ports:
        - containerPort: 8080
        env:
        - name: "APP_COLOR"
          value: "blue"

---
apiVersion: v1
kind: Service
metadata:
  name: service-blue
  namespace: blue-app
spec:
  selector:
    app: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blue
  namespace: blue-app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:  
  rules:
    - http:
        paths:
        - path: /blue
          pathType: Prefix
          backend:
            service:
              name: service-blue
              port:
                number: 80